// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_shadow_of_legends = "CgkIuOen94EGEAIQDg"; // <GPGSID>
        public const string achievement_escape_champion = "CgkIuOen94EGEAIQDA"; // <GPGSID>
        public const string achievement_eternal_survivor = "CgkIuOen94EGEAIQCQ"; // <GPGSID>
        public const string leaderboard_arrow_escape_masters = "CgkIuOen94EGEAIQAw"; // <GPGSID>
        public const string achievement_legend_of_escape = "CgkIuOen94EGEAIQBQ"; // <GPGSID>
        public const string achievement_beyond_limits = "CgkIuOen94EGEAIQDQ"; // <GPGSID>
        public const string achievement_path_finder = "CgkIuOen94EGEAIQEQ"; // <GPGSID>
        public const string achievement_arrow_dodger = "CgkIuOen94EGEAIQBw"; // <GPGSID>
        public const string achievement_rookie_escaper = "CgkIuOen94EGEAIQCw"; // <GPGSID>
        public const string achievement_arrow_conqueror = "CgkIuOen94EGEAIQDw"; // <GPGSID>
        public const string achievement_survival_master = "CgkIuOen94EGEAIQCg"; // <GPGSID>
        public const string achievement_arrow_whisperer = "CgkIuOen94EGEAIQBA"; // <GPGSID>
        public const string achievement_phantom_runner = "CgkIuOen94EGEAIQCA"; // <GPGSID>
        public const string achievement_escape_overload = "CgkIuOen94EGEAIQEA"; // <GPGSID>
        public const string achievement_escape_veteran = "CgkIuOen94EGEAIQBg"; // <GPGSID>

}

