// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_shadow_of_legends = "CgkI9__XresDEAIQCw"; // <GPGSID>
        public const string achievement_escape_champion = "CgkI9__XresDEAIQCQ"; // <GPGSID>
        public const string achievement_eternal_survivor = "CgkI9__XresDEAIQBg"; // <GPGSID>
        public const string achievement_legend_of_escape = "CgkI9__XresDEAIQAg"; // <GPGSID>
        public const string achievement_beyond_limits = "CgkI9__XresDEAIQCg"; // <GPGSID>
        public const string achievement_path_finder = "CgkI9__XresDEAIQDg"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI9__XresDEAIQDw"; // <GPGSID>
        public const string achievement_arrow_dodger = "CgkI9__XresDEAIQBA"; // <GPGSID>
        public const string achievement_rookie_escaper = "CgkI9__XresDEAIQCA"; // <GPGSID>
        public const string achievement_arrow_conqueror = "CgkI9__XresDEAIQDA"; // <GPGSID>
        public const string achievement_survival_master = "CgkI9__XresDEAIQBw"; // <GPGSID>
        public const string achievement_arrow_whisperer = "CgkI9__XresDEAIQAQ"; // <GPGSID>
        public const string achievement_phantom_runner = "CgkI9__XresDEAIQBQ"; // <GPGSID>
        public const string achievement_escape_overload = "CgkI9__XresDEAIQDQ"; // <GPGSID>
        public const string achievement_escape_veteran = "CgkI9__XresDEAIQAw"; // <GPGSID>

}

